# Generated by Django 4.1.6 on 2023-03-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='dp',
            field=models.ImageField(upload_to='photos/dp'),
        ),
    ]
